#nginx 실행 명령어: nginx -p ${PWD} -c ${PWD}/nginx.conf

daemon off; #to run in current terminal(available Ctrl + C for studying purpose)

events {
    worker_connections 2048; #number of network connections per process. 
}

http {
    # 경로 관련 트러블슈팅은 study.txt에 메모해둠. 확인하자. 
    access_log logs/nginx-access.log; # for studying purpose. to print log in terminal
    # error_log dev/stderr info; 
    error_log logs/nginx-error.log; #NGINX는 기본적으로 시스템 폴더인 var/log/nginx에 기록하지만, idx에선 보안상 이유로 해당 폴더에 접근하거나, 파일 생성할 권한이 없음

    upstream my-load-balanced-app {
        server 127.0.0.1:8081 weight=3;
        server 127.0.0.1:8082;
        server 127.0.0.1:8083;
        server 127.0.0.1:8084;

        # (참고) 특정 서버로 요청을 더 많이 보내고 싶다면 가중치 설정도 가능
        # server 127.0.0.1:3001 weight=3;
    }

    server {
        listen 8080; 
        location / {
            proxy_pass http://my-load-balanced-app; 
        }
    }
}
